//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotel_nn.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost\\SQLEXPRESS01;Initial Catalog=dbhotel2710376;Integrated Secu" +
            "rity=True")]
        public string dbhotel2710376ConnectionString {
            get {
                return ((string)(this["dbhotel2710376ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MEDAPRCSGFSD808;Initial Catalog=dbhotel2710376;Integrated Security=Tr" +
            "ue")]
        public string dbhotel {
            get {
                return ((string)(this["dbhotel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-13D56RL\\SIMONSQL;Initial Catalog=dbhotel2710376;Persist Secur" +
            "ity Info=True;User ID=sa;Password=Jokala123")]
        public string dbhotel2710376ConnectionString1 {
            get {
                return ((string)(this["dbhotel2710376ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-13D56RL\\SIMONSQL;Initial Catalog=dbhotel2710376;Integrated Se" +
            "curity=True")]
        public string dbhotel2710376ConnectionString2 {
            get {
                return ((string)(this["dbhotel2710376ConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MEDAPRCSGFD814;Initial Catalog=dbhotel2710376;Integrated Security=Tru" +
            "e")]
        public string dbhotel2710376ConnectionString3 {
            get {
                return ((string)(this["dbhotel2710376ConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MEDAPRCSGFSD808;Initial Catalog=ritmo_software;Integrated Security=Tr" +
            "ue")]
        public string ritmo_softwareConnectionString {
            get {
                return ((string)(this["ritmo_softwareConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost\\SQLEXPRESS01;Initial Catalog=ritmo_software;TrustServerCert" +
            "ificate=True;Integrated Security=True")]
        public string pc_camilo {
            get {
                return ((string)(this["pc_camilo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost\\SQLEXPRESS01;Initial Catalog=ritmo_software;User ID=sa;Pass" +
            "word=dominic;TrustServerCertificate=True;Integrated Security=True")]
        public string dominic {
            get {
                return ((string)(this["dominic"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost\\SQLEXPRESS01;Initial Catalog=ritmo_software;Integrated Secu" +
            "rity=True;TrustServerCertificate=True")]
        public string ritmo_softwareConnectionString1 {
            get {
                return ((string)(this["ritmo_softwareConnectionString1"]));
            }
        }
    }
}
